name: Build Linux

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "The name of the uploaded artifact"
        value: YinYue-linux

jobs:
  build-linux:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            qt_arch: gcc_64
            platform: x86_64-linux-gnu
          - arch: arm64
            qt_arch: gcc_arm64
            platform: aarch64-linux-gnu
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: linux
        target: 'desktop'
        arch: ${{ matrix.qt_arch }}
        cache: true
        setup-python: false
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        extra: '--external 7z'

    - name: Install Dependencies
      run: |
        sudo dpkg --add-architecture ${{ matrix.arch }}
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build \
          crossbuild-essential-${{ matrix.arch }} \
          libunwind-dev:${{ matrix.arch }} \
          libgl1-mesa-dev:${{ matrix.arch }} \
          libpulse-dev:${{ matrix.arch }} \
          libasound2-dev:${{ matrix.arch }} \
          libgstreamer1.0-dev:${{ matrix.arch }} \
          libgstreamer-plugins-base1.0-dev:${{ matrix.arch }} \
          gstreamer1.0-plugins-base:${{ matrix.arch }} \
          gstreamer1.0-plugins-good:${{ matrix.arch }} \
          gstreamer1.0-plugins-bad:${{ matrix.arch }} \
          gstreamer1.0-plugins-ugly:${{ matrix.arch }} \
          gstreamer1.0-libav:${{ matrix.arch }} \
          qtbase5-dev:${{ matrix.arch }} \
          qtmultimedia5-dev:${{ matrix.arch }} \
          qttools5-dev:${{ matrix.arch }} \
          qttools5-dev-tools:${{ matrix.arch }} \
          libqt5multimedia5-plugins:${{ matrix.arch }}

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -GNinja \
          -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.platform }} \
          -DCMAKE_CROSSCOMPILING=ON \
          ..

    - name: Build
      run: |
        cd build
        ninja

    - name: Package
      run: |
        cd build
        cpack -G DEB

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YinYue-linux-${{ matrix.arch }}
        path: build/*.deb
        retention-days: 1 