name: Build and Package

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  linux:
    uses: ./.github/workflows/build-linux.yml

  windows:
    uses: ./.github/workflows/build-windows.yml

  collect-artifacts:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: YinYue-*
        merge-multiple: true

    - name: Create Release Packages
      run: |
        cd artifacts
        zip -r YinYue-windows-x64.zip YinYue-windows-x64/*
        tar czf YinYue-linux-amd64.tar.gz YinYue-linux-amd64/YinYue

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/YinYue-windows-x64.zip
          artifacts/YinYue-linux-amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 