name: Build Linux

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "The name of the uploaded artifact"
        value: YinYue-linux

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: linux
        target: 'desktop'
        arch: gcc_64
        cache: true
        setup-python: false
        tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
        extra: '--external 7z'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build \
          libunwind-dev libgl1-mesa-dev \
          libpulse-dev libasound2-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          qtbase5-dev \
          qtmultimedia5-dev \
          qttools5-dev \
          qttools5-dev-tools \
          libqt5multimedia5-plugins

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -GNinja ..

    - name: Build
      run: |
        cd build
        ninja

    - name: Package
      run: |
        cd build
        cpack -G DEB

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YinYue-linux
        path: build/*.deb
        retention-days: 1 