name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List available Qt modules
      run: |
        python3 -m pip install aqtinstall
        aqt list-qt linux desktop --modules 5.15.2 gcc_64

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        tools: 'tools_qtcreator,qt.tools.qtcreator'
        cache: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build \
          libgl1-mesa-dev libpulse-dev libasound2-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          qt5-default qtmultimedia5-dev qttools5-dev-tools

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake -GNinja ..

    - name: Build
      run: |
        cd build
        ninja

    - name: Package
      run: |
        cd build
        cpack -G DEB

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YinYue-linux
        path: build/YinYue*.deb

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/YinYue*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 