name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  linux:
    uses: ./.github/workflows/build-linux.yml

  windows:
    uses: ./.github/workflows/build-windows.yml

  collect-artifacts:
    needs: [linux, windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: YinYue-*
        merge-multiple: true

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*.deb
          artifacts/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}