name: Build Windows

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "The name of the uploaded artifact"
        value: YinYue-windows

jobs:
  build-windows:
    strategy:
      matrix:
        arch: [x64]
        include:
          - arch: x64
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: |
          C:/vcpkg
          !C:/vcpkg/buildtrees
          !C:/vcpkg/packages
          !C:/vcpkg/downloads
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git C:/vcpkg
        C:/vcpkg/bootstrap-vcpkg.bat
        C:/vcpkg/vcpkg integrate install

    - name: Install Qt (static)
      run: |
        C:/vcpkg/vcpkg install qt5-base:x64-windows-static qt5-multimedia:x64-windows-static qt5-tools:x64-windows-static

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Install Dependencies
      shell: bash
      run: |
        choco install ninja cmake

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.msvc_arch }}

    - name: Configure CMake
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -GNinja \
          -DCMAKE_C_COMPILER=cl.exe \
          -DCMAKE_CXX_COMPILER=cl.exe \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_SYSTEM_NAME=Windows \
          -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=x64-windows-static \
          ..

    - name: Build
      shell: bash
      run: |
        cd build
        ninja

    - name: Package
      shell: bash
      run: |
        cd build
        mkdir -p package
        cp YinYue.exe package/
        cd package
        7z a ../YinYue-windows-x64.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YinYue-windows-x64
        path: build/YinYue-windows-x64.zip
        retention-days: 1 